version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: code-evo-be0.1
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL
      - MONGODB_URL
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - CORS_ORIGINS
      - DISABLE_OPENAPI
    depends_on:
      - redis
      - chromadb

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  chromadb:
    image: ghcr.io/chroma/chroma:latest
    ports:
      - "8000:8000"
    restart: unless-stopped
