name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports: [6379]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/backend/requirements.prod.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.prod.txt

      - name: Run DB migrations (alembic)
        if: ${{ secrets.DATABASE_URL != '' }}
        working-directory: backend
        run: |
          echo "DATABASE_URL provided - running alembic upgrade head"
          python -m pip install --upgrade pip
          pip install alembic
          export DATABASE_URL="${{ secrets.DATABASE_URL }}"
          alembic upgrade head

      - name: Lint (ruff)
        run: |
          pip install ruff
          ruff check . || true

      - name: Run unit tests
        working-directory: backend
        run: |
          pip install pytest
          pytest -q || true

      - name: Build Docker image
        run: |
          docker build -f backend/Dockerfile.prod -t code-evo-be:ci .

      - name: Smoke test container
        run: |
          # Disable Ollama discovery in CI (no Ollama service in runner) to avoid long retries
          docker run --rm -d --name smoke -p 8080:8080 -e DISABLE_OLLAMA_DISCOVERY=1 code-evo-be:ci /bin/sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --app-dir /app/backend"
          sleep 5
          curl -fS http://127.0.0.1:8080/health || (docker logs smoke && exit 1)
          docker rm -f smoke
