name: Publish Backend Image to GHCR

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  migrate-staging:
    if: ${{ secrets.STAGING_DATABASE_URL != '' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install alembic

      - name: Run alembic migrations against staging DB
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
        run: |
          echo "Running alembic upgrade head against staging"
          alembic upgrade head

  build-and-push:
    needs: migrate-staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # Prefer a user-provided GHCR_PAT secret (recommended) but fall back to GITHUB_TOKEN
          password: ${{ secrets.GHCR_PAT != '' && secrets.GHCR_PAT || secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/code-evo-backend:latest
            ghcr.io/${{ github.repository_owner }}/code-evo-backend:${{ github.sha }}
          platforms: linux/amd64

      - name: Show published image
        run: |
          echo "Published: ghcr.io/${{ github.repository_owner }}/code-evo-backend:latest"
